# Generated by Django 5.2.7 on 2025-10-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(db_index=True, max_length=20, unique=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('allow_retakes', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=3, help_text='0 means unlimited')),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('auto_score', models.IntegerField(default=0, help_text='Auto-graded score')),
                ('total_possible', models.IntegerField(default=0, help_text='Total possible points')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='llm_response',
            field=models.JSONField(blank=True, help_text='Raw LLM JSON response', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher_prompt',
            field=models.TextField(default=1, help_text='Original teacher request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'order'], name='quizapp_que_test_id_e94021_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['teacher', '-created_at'], name='quizapp_tes_teacher_35e414_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='quizapp_use_telegra_6f462d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='quizapp_use_role_8297b9_idx'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quizapp.test'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizapp.assignment'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizapp.user'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizapp.studentattempt'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['access_token'], name='quizapp_ass_access__5ff008_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['test', 'is_active'], name='quizapp_ass_test_id_903f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['assignment', 'student'], name='quizapp_stu_assignm_a891f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['student', '-started_at'], name='quizapp_stu_student_c88fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['assignment', 'is_completed'], name='quizapp_stu_assignm_3dc624_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattempt',
            unique_together={('assignment', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='quizapp_stu_attempt_49c8be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
