# Generated by Django 5.2.7 on 2025-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['question__order']},
        ),
        migrations.AddField(
            model_name='test',
            name='creation_method',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manual Input')], default='ai', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher_prompt',
            field=models.TextField(blank=True, help_text='Original teacher request'),
        ),
    ]
