# Generated by Django 5.2.7 on 2025-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
