# Generated by Django 5.2.7 on 2025-11-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_studentanswer_options_test_creation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='is_terminated',
            field=models.BooleanField(default=False, help_text='Test terminated due to cheating'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='questions_answered',
            field=models.IntegerField(default=0, help_text='Number of questions answered before termination'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='termination_reason',
            field=models.CharField(blank=True, help_text='Reason for termination', max_length=255),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, help_text='Time taken to complete in seconds', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='timer_minutes',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes (leave empty for no limit)', null=True),
        ),
    ]
