# Generated by Django 5.2.7 on 2025-12-22 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_studentattempt_is_terminated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(help_text='1-10 for Group-1 to Group-10', unique=True)),
                ('access_token', models.CharField(db_index=True, max_length=20, unique=True)),
                ('timer_minutes', models.IntegerField(help_text='Time limit for the test')),
                ('max_group_size', models.IntegerField(default=10, help_text='Maximum students per group')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tests_created', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tests', to='quizapp.test')),
            ],
            options={
                'ordering': ['group_number'],
                'unique_together': {('teacher', 'group_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('group_score_percentage', models.FloatField(default=0.0, help_text='Group answer score 0-100%')),
                ('total_possible', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizapp.grouptest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(help_text="Group's selected option index")),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
                ('submitted_by', models.ForeignKey(help_text='Who clicked submit', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizapp.groupattempt')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('group_attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_score_percentage', models.FloatField(default=0.0, help_text='Individual contribution 0-100%')),
                ('has_submitted_all_opinions', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='quizapp.groupattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('group_attempt', 'student')},
            },
        ),
        migrations.CreateModel(
            name='IndividualOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_text', models.TextField(help_text="Student's individual thinking")),
                ('score_percentage', models.FloatField(default=0.0, help_text='AI-evaluated quality 0-100%')),
                ('ai_feedback', models.TextField(blank=True, help_text="AI's brief feedback")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('group_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='quizapp.groupattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question__order', 'submitted_at'],
                'unique_together': {('group_attempt', 'question', 'student')},
            },
        ),
    ]
