# Generated by Django 5.2.7 on 2025-12-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_grouptest_groupattempt_groupanswer_groupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text="For open-ended: Group's text answer", null=True),
        ),
        migrations.AlterField(
            model_name='groupanswer',
            name='selected_option',
            field=models.IntegerField(default=0, help_text="For MCQ: Group's selected option index"),
        ),
    ]
